/*
 * generated by Xtext 2.14.0
 */
package org.xtext.example.activitydiagramdsl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class ActivityDiagramDslAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/xtext/example/activitydiagramdsl/parser/antlr/internal/InternalActivityDiagramDsl.tokens");
	}
}
