/**
 * generated by Xtext 2.14.0
 */
package org.xtext.example.activitydiagramdsl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.example.activitydiagramdsl.ActivityDiagramDslRuntimeModule;
import org.xtext.example.activitydiagramdsl.ActivityDiagramDslStandaloneSetup;
import org.xtext.example.activitydiagramdsl.ide.ActivityDiagramDslIdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class ActivityDiagramDslIdeSetup extends ActivityDiagramDslStandaloneSetup {
  @Override
  public Injector createInjector() {
    ActivityDiagramDslRuntimeModule _activityDiagramDslRuntimeModule = new ActivityDiagramDslRuntimeModule();
    ActivityDiagramDslIdeModule _activityDiagramDslIdeModule = new ActivityDiagramDslIdeModule();
    return Guice.createInjector(Modules2.mixin(_activityDiagramDslRuntimeModule, _activityDiagramDslIdeModule));
  }
}
