/**
 * generated by Xtext 2.14.0
 */
package org.xtext.example.activitydiagramdsl.ide;

import org.xtext.example.activitydiagramdsl.ide.AbstractActivityDiagramDslIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class ActivityDiagramDslIdeModule extends AbstractActivityDiagramDslIdeModule {
}
