/**
 * generated by Xtext 2.14.0
 */
package org.xtext.example.activitydiagramdsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.xtext.example.activitydiagramdsl.ui.AbstractActivityDiagramDslUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class ActivityDiagramDslUiModule extends AbstractActivityDiagramDslUiModule {
  public ActivityDiagramDslUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
