/**
 * generated by Xtext 2.14.0
 */
package org.xtext.example.activitydiagramdsl;

import org.xtext.example.activitydiagramdsl.AbstractActivityDiagramDslRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class ActivityDiagramDslRuntimeModule extends AbstractActivityDiagramDslRuntimeModule {
}
