/**
 * generated by Xtext 2.14.0
 */
package org.xtext.example.activitydiagramdsl;

import org.xtext.example.activitydiagramdsl.ActivityDiagramDslStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class ActivityDiagramDslStandaloneSetup extends ActivityDiagramDslStandaloneSetupGenerated {
  public static void doSetup() {
    new ActivityDiagramDslStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
