/*
 * generated by Xtext 2.14.0
 */
package org.xtext.example.activitydiagramdsl.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractGrammarElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class ActivityDiagramDslGrammarAccess extends AbstractGrammarElementFinder {
	
	public class ActivityDiagramElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.activitydiagramdsl.ActivityDiagramDsl.ActivityDiagram");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cActivityDiagramAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cActivityDiagramKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cInitialNodeKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cInitialNodeAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cInitialNodeInitialNodeParserRuleCall_4_1_0 = (RuleCall)cInitialNodeAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cFinalNodeKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cFinalNodeAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cFinalNodeFinalNodeParserRuleCall_5_1_0 = (RuleCall)cFinalNodeAssignment_5_1.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cTrasitionsKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_6_1 = (Keyword)cGroup_6.eContents().get(1);
		private final Assignment cTrasitionsAssignment_6_2 = (Assignment)cGroup_6.eContents().get(2);
		private final RuleCall cTrasitionsTransitionParserRuleCall_6_2_0 = (RuleCall)cTrasitionsAssignment_6_2.eContents().get(0);
		private final Group cGroup_6_3 = (Group)cGroup_6.eContents().get(3);
		private final Keyword cCommaKeyword_6_3_0 = (Keyword)cGroup_6_3.eContents().get(0);
		private final Assignment cTrasitionsAssignment_6_3_1 = (Assignment)cGroup_6_3.eContents().get(1);
		private final RuleCall cTrasitionsTransitionParserRuleCall_6_3_1_0 = (RuleCall)cTrasitionsAssignment_6_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6_4 = (Keyword)cGroup_6.eContents().get(4);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cActivityNodesKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_7_1 = (Keyword)cGroup_7.eContents().get(1);
		private final Assignment cActivityNodesAssignment_7_2 = (Assignment)cGroup_7.eContents().get(2);
		private final RuleCall cActivityNodesActivityNodeParserRuleCall_7_2_0 = (RuleCall)cActivityNodesAssignment_7_2.eContents().get(0);
		private final Group cGroup_7_3 = (Group)cGroup_7.eContents().get(3);
		private final Keyword cCommaKeyword_7_3_0 = (Keyword)cGroup_7_3.eContents().get(0);
		private final Assignment cActivityNodesAssignment_7_3_1 = (Assignment)cGroup_7_3.eContents().get(1);
		private final RuleCall cActivityNodesActivityNodeParserRuleCall_7_3_1_0 = (RuleCall)cActivityNodesAssignment_7_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7_4 = (Keyword)cGroup_7.eContents().get(4);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cForkNodesKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_8_1 = (Keyword)cGroup_8.eContents().get(1);
		private final Assignment cForkNodesAssignment_8_2 = (Assignment)cGroup_8.eContents().get(2);
		private final RuleCall cForkNodesForkNodeParserRuleCall_8_2_0 = (RuleCall)cForkNodesAssignment_8_2.eContents().get(0);
		private final Group cGroup_8_3 = (Group)cGroup_8.eContents().get(3);
		private final Keyword cCommaKeyword_8_3_0 = (Keyword)cGroup_8_3.eContents().get(0);
		private final Assignment cForkNodesAssignment_8_3_1 = (Assignment)cGroup_8_3.eContents().get(1);
		private final RuleCall cForkNodesForkNodeParserRuleCall_8_3_1_0 = (RuleCall)cForkNodesAssignment_8_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_8_4 = (Keyword)cGroup_8.eContents().get(4);
		private final Group cGroup_9 = (Group)cGroup.eContents().get(9);
		private final Keyword cJoinNodesKeyword_9_0 = (Keyword)cGroup_9.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_9_1 = (Keyword)cGroup_9.eContents().get(1);
		private final Assignment cJoinNodesAssignment_9_2 = (Assignment)cGroup_9.eContents().get(2);
		private final RuleCall cJoinNodesJoinNodeParserRuleCall_9_2_0 = (RuleCall)cJoinNodesAssignment_9_2.eContents().get(0);
		private final Group cGroup_9_3 = (Group)cGroup_9.eContents().get(3);
		private final Keyword cCommaKeyword_9_3_0 = (Keyword)cGroup_9_3.eContents().get(0);
		private final Assignment cJoinNodesAssignment_9_3_1 = (Assignment)cGroup_9_3.eContents().get(1);
		private final RuleCall cJoinNodesJoinNodeParserRuleCall_9_3_1_0 = (RuleCall)cJoinNodesAssignment_9_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_9_4 = (Keyword)cGroup_9.eContents().get(4);
		private final Group cGroup_10 = (Group)cGroup.eContents().get(10);
		private final Keyword cDecisionNodesKeyword_10_0 = (Keyword)cGroup_10.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_10_1 = (Keyword)cGroup_10.eContents().get(1);
		private final Assignment cDecisionNodesAssignment_10_2 = (Assignment)cGroup_10.eContents().get(2);
		private final RuleCall cDecisionNodesDecisionNodeParserRuleCall_10_2_0 = (RuleCall)cDecisionNodesAssignment_10_2.eContents().get(0);
		private final Group cGroup_10_3 = (Group)cGroup_10.eContents().get(3);
		private final Keyword cCommaKeyword_10_3_0 = (Keyword)cGroup_10_3.eContents().get(0);
		private final Assignment cDecisionNodesAssignment_10_3_1 = (Assignment)cGroup_10_3.eContents().get(1);
		private final RuleCall cDecisionNodesDecisionNodeParserRuleCall_10_3_1_0 = (RuleCall)cDecisionNodesAssignment_10_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_10_4 = (Keyword)cGroup_10.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_11 = (Keyword)cGroup.eContents().get(11);
		
		//ActivityDiagram:
		//	{ActivityDiagram}
		//	'ActivityDiagram'
		//	name=EString
		//	'{' ('initialNode' initialNode=InitialNode)? ('finalNode' finalNode=FinalNode)? ('trasitions' '{'
		//	trasitions+=Transition ("," trasitions+=Transition)* '}')? ('activityNodes' '{' activityNodes+=ActivityNode (","
		//	activityNodes+=ActivityNode)* '}')? ('forkNodes' '{' forkNodes+=ForkNode ("," forkNodes+=ForkNode)* '}')?
		//	('joinNodes' '{' joinNodes+=JoinNode ("," joinNodes+=JoinNode)* '}')? ('decisionNodes' '{'
		//	decisionNodes+=DecisionNode ("," decisionNodes+=DecisionNode)* '}')?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{ActivityDiagram} 'ActivityDiagram' name=EString '{' ('initialNode' initialNode=InitialNode)? ('finalNode'
		//finalNode=FinalNode)? ('trasitions' '{' trasitions+=Transition ("," trasitions+=Transition)* '}')? ('activityNodes'
		//'{' activityNodes+=ActivityNode ("," activityNodes+=ActivityNode)* '}')? ('forkNodes' '{' forkNodes+=ForkNode (","
		//forkNodes+=ForkNode)* '}')? ('joinNodes' '{' joinNodes+=JoinNode ("," joinNodes+=JoinNode)* '}')? ('decisionNodes' '{'
		//decisionNodes+=DecisionNode ("," decisionNodes+=DecisionNode)* '}')? '}'
		public Group getGroup() { return cGroup; }
		
		//{ActivityDiagram}
		public Action getActivityDiagramAction_0() { return cActivityDiagramAction_0; }
		
		//'ActivityDiagram'
		public Keyword getActivityDiagramKeyword_1() { return cActivityDiagramKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('initialNode' initialNode=InitialNode)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'initialNode'
		public Keyword getInitialNodeKeyword_4_0() { return cInitialNodeKeyword_4_0; }
		
		//initialNode=InitialNode
		public Assignment getInitialNodeAssignment_4_1() { return cInitialNodeAssignment_4_1; }
		
		//InitialNode
		public RuleCall getInitialNodeInitialNodeParserRuleCall_4_1_0() { return cInitialNodeInitialNodeParserRuleCall_4_1_0; }
		
		//('finalNode' finalNode=FinalNode)?
		public Group getGroup_5() { return cGroup_5; }
		
		//'finalNode'
		public Keyword getFinalNodeKeyword_5_0() { return cFinalNodeKeyword_5_0; }
		
		//finalNode=FinalNode
		public Assignment getFinalNodeAssignment_5_1() { return cFinalNodeAssignment_5_1; }
		
		//FinalNode
		public RuleCall getFinalNodeFinalNodeParserRuleCall_5_1_0() { return cFinalNodeFinalNodeParserRuleCall_5_1_0; }
		
		//('trasitions' '{' trasitions+=Transition ("," trasitions+=Transition)* '}')?
		public Group getGroup_6() { return cGroup_6; }
		
		//'trasitions'
		public Keyword getTrasitionsKeyword_6_0() { return cTrasitionsKeyword_6_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_6_1() { return cLeftCurlyBracketKeyword_6_1; }
		
		//trasitions+=Transition
		public Assignment getTrasitionsAssignment_6_2() { return cTrasitionsAssignment_6_2; }
		
		//Transition
		public RuleCall getTrasitionsTransitionParserRuleCall_6_2_0() { return cTrasitionsTransitionParserRuleCall_6_2_0; }
		
		//("," trasitions+=Transition)*
		public Group getGroup_6_3() { return cGroup_6_3; }
		
		//","
		public Keyword getCommaKeyword_6_3_0() { return cCommaKeyword_6_3_0; }
		
		//trasitions+=Transition
		public Assignment getTrasitionsAssignment_6_3_1() { return cTrasitionsAssignment_6_3_1; }
		
		//Transition
		public RuleCall getTrasitionsTransitionParserRuleCall_6_3_1_0() { return cTrasitionsTransitionParserRuleCall_6_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6_4() { return cRightCurlyBracketKeyword_6_4; }
		
		//('activityNodes' '{' activityNodes+=ActivityNode ("," activityNodes+=ActivityNode)* '}')?
		public Group getGroup_7() { return cGroup_7; }
		
		//'activityNodes'
		public Keyword getActivityNodesKeyword_7_0() { return cActivityNodesKeyword_7_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_7_1() { return cLeftCurlyBracketKeyword_7_1; }
		
		//activityNodes+=ActivityNode
		public Assignment getActivityNodesAssignment_7_2() { return cActivityNodesAssignment_7_2; }
		
		//ActivityNode
		public RuleCall getActivityNodesActivityNodeParserRuleCall_7_2_0() { return cActivityNodesActivityNodeParserRuleCall_7_2_0; }
		
		//("," activityNodes+=ActivityNode)*
		public Group getGroup_7_3() { return cGroup_7_3; }
		
		//","
		public Keyword getCommaKeyword_7_3_0() { return cCommaKeyword_7_3_0; }
		
		//activityNodes+=ActivityNode
		public Assignment getActivityNodesAssignment_7_3_1() { return cActivityNodesAssignment_7_3_1; }
		
		//ActivityNode
		public RuleCall getActivityNodesActivityNodeParserRuleCall_7_3_1_0() { return cActivityNodesActivityNodeParserRuleCall_7_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7_4() { return cRightCurlyBracketKeyword_7_4; }
		
		//('forkNodes' '{' forkNodes+=ForkNode ("," forkNodes+=ForkNode)* '}')?
		public Group getGroup_8() { return cGroup_8; }
		
		//'forkNodes'
		public Keyword getForkNodesKeyword_8_0() { return cForkNodesKeyword_8_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_8_1() { return cLeftCurlyBracketKeyword_8_1; }
		
		//forkNodes+=ForkNode
		public Assignment getForkNodesAssignment_8_2() { return cForkNodesAssignment_8_2; }
		
		//ForkNode
		public RuleCall getForkNodesForkNodeParserRuleCall_8_2_0() { return cForkNodesForkNodeParserRuleCall_8_2_0; }
		
		//("," forkNodes+=ForkNode)*
		public Group getGroup_8_3() { return cGroup_8_3; }
		
		//","
		public Keyword getCommaKeyword_8_3_0() { return cCommaKeyword_8_3_0; }
		
		//forkNodes+=ForkNode
		public Assignment getForkNodesAssignment_8_3_1() { return cForkNodesAssignment_8_3_1; }
		
		//ForkNode
		public RuleCall getForkNodesForkNodeParserRuleCall_8_3_1_0() { return cForkNodesForkNodeParserRuleCall_8_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_8_4() { return cRightCurlyBracketKeyword_8_4; }
		
		//('joinNodes' '{' joinNodes+=JoinNode ("," joinNodes+=JoinNode)* '}')?
		public Group getGroup_9() { return cGroup_9; }
		
		//'joinNodes'
		public Keyword getJoinNodesKeyword_9_0() { return cJoinNodesKeyword_9_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_9_1() { return cLeftCurlyBracketKeyword_9_1; }
		
		//joinNodes+=JoinNode
		public Assignment getJoinNodesAssignment_9_2() { return cJoinNodesAssignment_9_2; }
		
		//JoinNode
		public RuleCall getJoinNodesJoinNodeParserRuleCall_9_2_0() { return cJoinNodesJoinNodeParserRuleCall_9_2_0; }
		
		//("," joinNodes+=JoinNode)*
		public Group getGroup_9_3() { return cGroup_9_3; }
		
		//","
		public Keyword getCommaKeyword_9_3_0() { return cCommaKeyword_9_3_0; }
		
		//joinNodes+=JoinNode
		public Assignment getJoinNodesAssignment_9_3_1() { return cJoinNodesAssignment_9_3_1; }
		
		//JoinNode
		public RuleCall getJoinNodesJoinNodeParserRuleCall_9_3_1_0() { return cJoinNodesJoinNodeParserRuleCall_9_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_9_4() { return cRightCurlyBracketKeyword_9_4; }
		
		//('decisionNodes' '{' decisionNodes+=DecisionNode ("," decisionNodes+=DecisionNode)* '}')?
		public Group getGroup_10() { return cGroup_10; }
		
		//'decisionNodes'
		public Keyword getDecisionNodesKeyword_10_0() { return cDecisionNodesKeyword_10_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_10_1() { return cLeftCurlyBracketKeyword_10_1; }
		
		//decisionNodes+=DecisionNode
		public Assignment getDecisionNodesAssignment_10_2() { return cDecisionNodesAssignment_10_2; }
		
		//DecisionNode
		public RuleCall getDecisionNodesDecisionNodeParserRuleCall_10_2_0() { return cDecisionNodesDecisionNodeParserRuleCall_10_2_0; }
		
		//("," decisionNodes+=DecisionNode)*
		public Group getGroup_10_3() { return cGroup_10_3; }
		
		//","
		public Keyword getCommaKeyword_10_3_0() { return cCommaKeyword_10_3_0; }
		
		//decisionNodes+=DecisionNode
		public Assignment getDecisionNodesAssignment_10_3_1() { return cDecisionNodesAssignment_10_3_1; }
		
		//DecisionNode
		public RuleCall getDecisionNodesDecisionNodeParserRuleCall_10_3_1_0() { return cDecisionNodesDecisionNodeParserRuleCall_10_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_10_4() { return cRightCurlyBracketKeyword_10_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_11() { return cRightCurlyBracketKeyword_11; }
	}
	public class NodeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.activitydiagramdsl.ActivityDiagramDsl.Node");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cNode_ImplParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cFinalNodeParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cInitialNodeParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cActivityNodeParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		private final RuleCall cDecisionNodeParserRuleCall_4 = (RuleCall)cAlternatives.eContents().get(4);
		private final RuleCall cForkNodeParserRuleCall_5 = (RuleCall)cAlternatives.eContents().get(5);
		private final RuleCall cJoinNodeParserRuleCall_6 = (RuleCall)cAlternatives.eContents().get(6);
		
		//Node:
		//	Node_Impl | FinalNode | InitialNode | ActivityNode | DecisionNode | ForkNode | JoinNode;
		@Override public ParserRule getRule() { return rule; }
		
		//Node_Impl | FinalNode | InitialNode | ActivityNode | DecisionNode | ForkNode | JoinNode
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Node_Impl
		public RuleCall getNode_ImplParserRuleCall_0() { return cNode_ImplParserRuleCall_0; }
		
		//FinalNode
		public RuleCall getFinalNodeParserRuleCall_1() { return cFinalNodeParserRuleCall_1; }
		
		//InitialNode
		public RuleCall getInitialNodeParserRuleCall_2() { return cInitialNodeParserRuleCall_2; }
		
		//ActivityNode
		public RuleCall getActivityNodeParserRuleCall_3() { return cActivityNodeParserRuleCall_3; }
		
		//DecisionNode
		public RuleCall getDecisionNodeParserRuleCall_4() { return cDecisionNodeParserRuleCall_4; }
		
		//ForkNode
		public RuleCall getForkNodeParserRuleCall_5() { return cForkNodeParserRuleCall_5; }
		
		//JoinNode
		public RuleCall getJoinNodeParserRuleCall_6() { return cJoinNodeParserRuleCall_6; }
	}
	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.activitydiagramdsl.ActivityDiagramDsl.EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString:
		//	STRING | ID;
		@Override public ParserRule getRule() { return rule; }
		
		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}
	public class InitialNodeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.activitydiagramdsl.ActivityDiagramDsl.InitialNode");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cInitialNodeAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cInitialNodeKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cIncomingKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cIncomingAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final CrossReference cIncomingTransitionCrossReference_4_2_0 = (CrossReference)cIncomingAssignment_4_2.eContents().get(0);
		private final RuleCall cIncomingTransitionEStringParserRuleCall_4_2_0_1 = (RuleCall)cIncomingTransitionCrossReference_4_2_0.eContents().get(1);
		private final Group cGroup_4_3 = (Group)cGroup_4.eContents().get(3);
		private final Keyword cCommaKeyword_4_3_0 = (Keyword)cGroup_4_3.eContents().get(0);
		private final Assignment cIncomingAssignment_4_3_1 = (Assignment)cGroup_4_3.eContents().get(1);
		private final CrossReference cIncomingTransitionCrossReference_4_3_1_0 = (CrossReference)cIncomingAssignment_4_3_1.eContents().get(0);
		private final RuleCall cIncomingTransitionEStringParserRuleCall_4_3_1_0_1 = (RuleCall)cIncomingTransitionCrossReference_4_3_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_4_4 = (Keyword)cGroup_4.eContents().get(4);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cOutgoingKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Assignment cOutgoingAssignment_5_2 = (Assignment)cGroup_5.eContents().get(2);
		private final CrossReference cOutgoingTransitionCrossReference_5_2_0 = (CrossReference)cOutgoingAssignment_5_2.eContents().get(0);
		private final RuleCall cOutgoingTransitionEStringParserRuleCall_5_2_0_1 = (RuleCall)cOutgoingTransitionCrossReference_5_2_0.eContents().get(1);
		private final Group cGroup_5_3 = (Group)cGroup_5.eContents().get(3);
		private final Keyword cCommaKeyword_5_3_0 = (Keyword)cGroup_5_3.eContents().get(0);
		private final Assignment cOutgoingAssignment_5_3_1 = (Assignment)cGroup_5_3.eContents().get(1);
		private final CrossReference cOutgoingTransitionCrossReference_5_3_1_0 = (CrossReference)cOutgoingAssignment_5_3_1.eContents().get(0);
		private final RuleCall cOutgoingTransitionEStringParserRuleCall_5_3_1_0_1 = (RuleCall)cOutgoingTransitionCrossReference_5_3_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_5_4 = (Keyword)cGroup_5.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//InitialNode:
		//	{InitialNode}
		//	'InitialNode'
		//	name=EString
		//	'{' ('incoming' '(' incoming+=[Transition|EString] ("," incoming+=[Transition|EString])* ')')? ('outgoing' '('
		//	outgoing+=[Transition|EString] ("," outgoing+=[Transition|EString])* ')')?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{InitialNode} 'InitialNode' name=EString '{' ('incoming' '(' incoming+=[Transition|EString] (","
		//incoming+=[Transition|EString])* ')')? ('outgoing' '(' outgoing+=[Transition|EString] (","
		//outgoing+=[Transition|EString])* ')')? '}'
		public Group getGroup() { return cGroup; }
		
		//{InitialNode}
		public Action getInitialNodeAction_0() { return cInitialNodeAction_0; }
		
		//'InitialNode'
		public Keyword getInitialNodeKeyword_1() { return cInitialNodeKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('incoming' '(' incoming+=[Transition|EString] ("," incoming+=[Transition|EString])* ')')?
		public Group getGroup_4() { return cGroup_4; }
		
		//'incoming'
		public Keyword getIncomingKeyword_4_0() { return cIncomingKeyword_4_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_4_1() { return cLeftParenthesisKeyword_4_1; }
		
		//incoming+=[Transition|EString]
		public Assignment getIncomingAssignment_4_2() { return cIncomingAssignment_4_2; }
		
		//[Transition|EString]
		public CrossReference getIncomingTransitionCrossReference_4_2_0() { return cIncomingTransitionCrossReference_4_2_0; }
		
		//EString
		public RuleCall getIncomingTransitionEStringParserRuleCall_4_2_0_1() { return cIncomingTransitionEStringParserRuleCall_4_2_0_1; }
		
		//("," incoming+=[Transition|EString])*
		public Group getGroup_4_3() { return cGroup_4_3; }
		
		//","
		public Keyword getCommaKeyword_4_3_0() { return cCommaKeyword_4_3_0; }
		
		//incoming+=[Transition|EString]
		public Assignment getIncomingAssignment_4_3_1() { return cIncomingAssignment_4_3_1; }
		
		//[Transition|EString]
		public CrossReference getIncomingTransitionCrossReference_4_3_1_0() { return cIncomingTransitionCrossReference_4_3_1_0; }
		
		//EString
		public RuleCall getIncomingTransitionEStringParserRuleCall_4_3_1_0_1() { return cIncomingTransitionEStringParserRuleCall_4_3_1_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_4_4() { return cRightParenthesisKeyword_4_4; }
		
		//('outgoing' '(' outgoing+=[Transition|EString] ("," outgoing+=[Transition|EString])* ')')?
		public Group getGroup_5() { return cGroup_5; }
		
		//'outgoing'
		public Keyword getOutgoingKeyword_5_0() { return cOutgoingKeyword_5_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_5_1() { return cLeftParenthesisKeyword_5_1; }
		
		//outgoing+=[Transition|EString]
		public Assignment getOutgoingAssignment_5_2() { return cOutgoingAssignment_5_2; }
		
		//[Transition|EString]
		public CrossReference getOutgoingTransitionCrossReference_5_2_0() { return cOutgoingTransitionCrossReference_5_2_0; }
		
		//EString
		public RuleCall getOutgoingTransitionEStringParserRuleCall_5_2_0_1() { return cOutgoingTransitionEStringParserRuleCall_5_2_0_1; }
		
		//("," outgoing+=[Transition|EString])*
		public Group getGroup_5_3() { return cGroup_5_3; }
		
		//","
		public Keyword getCommaKeyword_5_3_0() { return cCommaKeyword_5_3_0; }
		
		//outgoing+=[Transition|EString]
		public Assignment getOutgoingAssignment_5_3_1() { return cOutgoingAssignment_5_3_1; }
		
		//[Transition|EString]
		public CrossReference getOutgoingTransitionCrossReference_5_3_1_0() { return cOutgoingTransitionCrossReference_5_3_1_0; }
		
		//EString
		public RuleCall getOutgoingTransitionEStringParserRuleCall_5_3_1_0_1() { return cOutgoingTransitionEStringParserRuleCall_5_3_1_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_5_4() { return cRightParenthesisKeyword_5_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	public class FinalNodeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.activitydiagramdsl.ActivityDiagramDsl.FinalNode");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cFinalNodeAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cFinalNodeKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cIncomingKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cIncomingAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final CrossReference cIncomingTransitionCrossReference_4_2_0 = (CrossReference)cIncomingAssignment_4_2.eContents().get(0);
		private final RuleCall cIncomingTransitionEStringParserRuleCall_4_2_0_1 = (RuleCall)cIncomingTransitionCrossReference_4_2_0.eContents().get(1);
		private final Group cGroup_4_3 = (Group)cGroup_4.eContents().get(3);
		private final Keyword cCommaKeyword_4_3_0 = (Keyword)cGroup_4_3.eContents().get(0);
		private final Assignment cIncomingAssignment_4_3_1 = (Assignment)cGroup_4_3.eContents().get(1);
		private final CrossReference cIncomingTransitionCrossReference_4_3_1_0 = (CrossReference)cIncomingAssignment_4_3_1.eContents().get(0);
		private final RuleCall cIncomingTransitionEStringParserRuleCall_4_3_1_0_1 = (RuleCall)cIncomingTransitionCrossReference_4_3_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_4_4 = (Keyword)cGroup_4.eContents().get(4);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cOutgoingKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Assignment cOutgoingAssignment_5_2 = (Assignment)cGroup_5.eContents().get(2);
		private final CrossReference cOutgoingTransitionCrossReference_5_2_0 = (CrossReference)cOutgoingAssignment_5_2.eContents().get(0);
		private final RuleCall cOutgoingTransitionEStringParserRuleCall_5_2_0_1 = (RuleCall)cOutgoingTransitionCrossReference_5_2_0.eContents().get(1);
		private final Group cGroup_5_3 = (Group)cGroup_5.eContents().get(3);
		private final Keyword cCommaKeyword_5_3_0 = (Keyword)cGroup_5_3.eContents().get(0);
		private final Assignment cOutgoingAssignment_5_3_1 = (Assignment)cGroup_5_3.eContents().get(1);
		private final CrossReference cOutgoingTransitionCrossReference_5_3_1_0 = (CrossReference)cOutgoingAssignment_5_3_1.eContents().get(0);
		private final RuleCall cOutgoingTransitionEStringParserRuleCall_5_3_1_0_1 = (RuleCall)cOutgoingTransitionCrossReference_5_3_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_5_4 = (Keyword)cGroup_5.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//FinalNode:
		//	{FinalNode}
		//	'FinalNode'
		//	name=EString
		//	'{' ('incoming' '(' incoming+=[Transition|EString] ("," incoming+=[Transition|EString])* ')')? ('outgoing' '('
		//	outgoing+=[Transition|EString] ("," outgoing+=[Transition|EString])* ')')?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{FinalNode} 'FinalNode' name=EString '{' ('incoming' '(' incoming+=[Transition|EString] (","
		//incoming+=[Transition|EString])* ')')? ('outgoing' '(' outgoing+=[Transition|EString] (","
		//outgoing+=[Transition|EString])* ')')? '}'
		public Group getGroup() { return cGroup; }
		
		//{FinalNode}
		public Action getFinalNodeAction_0() { return cFinalNodeAction_0; }
		
		//'FinalNode'
		public Keyword getFinalNodeKeyword_1() { return cFinalNodeKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('incoming' '(' incoming+=[Transition|EString] ("," incoming+=[Transition|EString])* ')')?
		public Group getGroup_4() { return cGroup_4; }
		
		//'incoming'
		public Keyword getIncomingKeyword_4_0() { return cIncomingKeyword_4_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_4_1() { return cLeftParenthesisKeyword_4_1; }
		
		//incoming+=[Transition|EString]
		public Assignment getIncomingAssignment_4_2() { return cIncomingAssignment_4_2; }
		
		//[Transition|EString]
		public CrossReference getIncomingTransitionCrossReference_4_2_0() { return cIncomingTransitionCrossReference_4_2_0; }
		
		//EString
		public RuleCall getIncomingTransitionEStringParserRuleCall_4_2_0_1() { return cIncomingTransitionEStringParserRuleCall_4_2_0_1; }
		
		//("," incoming+=[Transition|EString])*
		public Group getGroup_4_3() { return cGroup_4_3; }
		
		//","
		public Keyword getCommaKeyword_4_3_0() { return cCommaKeyword_4_3_0; }
		
		//incoming+=[Transition|EString]
		public Assignment getIncomingAssignment_4_3_1() { return cIncomingAssignment_4_3_1; }
		
		//[Transition|EString]
		public CrossReference getIncomingTransitionCrossReference_4_3_1_0() { return cIncomingTransitionCrossReference_4_3_1_0; }
		
		//EString
		public RuleCall getIncomingTransitionEStringParserRuleCall_4_3_1_0_1() { return cIncomingTransitionEStringParserRuleCall_4_3_1_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_4_4() { return cRightParenthesisKeyword_4_4; }
		
		//('outgoing' '(' outgoing+=[Transition|EString] ("," outgoing+=[Transition|EString])* ')')?
		public Group getGroup_5() { return cGroup_5; }
		
		//'outgoing'
		public Keyword getOutgoingKeyword_5_0() { return cOutgoingKeyword_5_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_5_1() { return cLeftParenthesisKeyword_5_1; }
		
		//outgoing+=[Transition|EString]
		public Assignment getOutgoingAssignment_5_2() { return cOutgoingAssignment_5_2; }
		
		//[Transition|EString]
		public CrossReference getOutgoingTransitionCrossReference_5_2_0() { return cOutgoingTransitionCrossReference_5_2_0; }
		
		//EString
		public RuleCall getOutgoingTransitionEStringParserRuleCall_5_2_0_1() { return cOutgoingTransitionEStringParserRuleCall_5_2_0_1; }
		
		//("," outgoing+=[Transition|EString])*
		public Group getGroup_5_3() { return cGroup_5_3; }
		
		//","
		public Keyword getCommaKeyword_5_3_0() { return cCommaKeyword_5_3_0; }
		
		//outgoing+=[Transition|EString]
		public Assignment getOutgoingAssignment_5_3_1() { return cOutgoingAssignment_5_3_1; }
		
		//[Transition|EString]
		public CrossReference getOutgoingTransitionCrossReference_5_3_1_0() { return cOutgoingTransitionCrossReference_5_3_1_0; }
		
		//EString
		public RuleCall getOutgoingTransitionEStringParserRuleCall_5_3_1_0_1() { return cOutgoingTransitionEStringParserRuleCall_5_3_1_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_5_4() { return cRightParenthesisKeyword_5_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	public class TransitionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.activitydiagramdsl.ActivityDiagramDsl.Transition");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cTransitionAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cTransitionKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cTargetKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cTargetAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final CrossReference cTargetNodeCrossReference_4_1_0 = (CrossReference)cTargetAssignment_4_1.eContents().get(0);
		private final RuleCall cTargetNodeEStringParserRuleCall_4_1_0_1 = (RuleCall)cTargetNodeCrossReference_4_1_0.eContents().get(1);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cSourceKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cSourceAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final CrossReference cSourceNodeCrossReference_5_1_0 = (CrossReference)cSourceAssignment_5_1.eContents().get(0);
		private final RuleCall cSourceNodeEStringParserRuleCall_5_1_0_1 = (RuleCall)cSourceNodeCrossReference_5_1_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//Transition:
		//	{Transition}
		//	'Transition'
		//	name=EString
		//	'{' ('target' target=[Node|EString])? ('source' source=[Node|EString])?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Transition} 'Transition' name=EString '{' ('target' target=[Node|EString])? ('source' source=[Node|EString])? '}'
		public Group getGroup() { return cGroup; }
		
		//{Transition}
		public Action getTransitionAction_0() { return cTransitionAction_0; }
		
		//'Transition'
		public Keyword getTransitionKeyword_1() { return cTransitionKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('target' target=[Node|EString])?
		public Group getGroup_4() { return cGroup_4; }
		
		//'target'
		public Keyword getTargetKeyword_4_0() { return cTargetKeyword_4_0; }
		
		//target=[Node|EString]
		public Assignment getTargetAssignment_4_1() { return cTargetAssignment_4_1; }
		
		//[Node|EString]
		public CrossReference getTargetNodeCrossReference_4_1_0() { return cTargetNodeCrossReference_4_1_0; }
		
		//EString
		public RuleCall getTargetNodeEStringParserRuleCall_4_1_0_1() { return cTargetNodeEStringParserRuleCall_4_1_0_1; }
		
		//('source' source=[Node|EString])?
		public Group getGroup_5() { return cGroup_5; }
		
		//'source'
		public Keyword getSourceKeyword_5_0() { return cSourceKeyword_5_0; }
		
		//source=[Node|EString]
		public Assignment getSourceAssignment_5_1() { return cSourceAssignment_5_1; }
		
		//[Node|EString]
		public CrossReference getSourceNodeCrossReference_5_1_0() { return cSourceNodeCrossReference_5_1_0; }
		
		//EString
		public RuleCall getSourceNodeEStringParserRuleCall_5_1_0_1() { return cSourceNodeEStringParserRuleCall_5_1_0_1; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	public class ActivityNodeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.activitydiagramdsl.ActivityDiagramDsl.ActivityNode");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cActivityNodeAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cActivityNodeKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cIncomingKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cIncomingAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final CrossReference cIncomingTransitionCrossReference_4_2_0 = (CrossReference)cIncomingAssignment_4_2.eContents().get(0);
		private final RuleCall cIncomingTransitionEStringParserRuleCall_4_2_0_1 = (RuleCall)cIncomingTransitionCrossReference_4_2_0.eContents().get(1);
		private final Group cGroup_4_3 = (Group)cGroup_4.eContents().get(3);
		private final Keyword cCommaKeyword_4_3_0 = (Keyword)cGroup_4_3.eContents().get(0);
		private final Assignment cIncomingAssignment_4_3_1 = (Assignment)cGroup_4_3.eContents().get(1);
		private final CrossReference cIncomingTransitionCrossReference_4_3_1_0 = (CrossReference)cIncomingAssignment_4_3_1.eContents().get(0);
		private final RuleCall cIncomingTransitionEStringParserRuleCall_4_3_1_0_1 = (RuleCall)cIncomingTransitionCrossReference_4_3_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_4_4 = (Keyword)cGroup_4.eContents().get(4);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cOutgoingKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Assignment cOutgoingAssignment_5_2 = (Assignment)cGroup_5.eContents().get(2);
		private final CrossReference cOutgoingTransitionCrossReference_5_2_0 = (CrossReference)cOutgoingAssignment_5_2.eContents().get(0);
		private final RuleCall cOutgoingTransitionEStringParserRuleCall_5_2_0_1 = (RuleCall)cOutgoingTransitionCrossReference_5_2_0.eContents().get(1);
		private final Group cGroup_5_3 = (Group)cGroup_5.eContents().get(3);
		private final Keyword cCommaKeyword_5_3_0 = (Keyword)cGroup_5_3.eContents().get(0);
		private final Assignment cOutgoingAssignment_5_3_1 = (Assignment)cGroup_5_3.eContents().get(1);
		private final CrossReference cOutgoingTransitionCrossReference_5_3_1_0 = (CrossReference)cOutgoingAssignment_5_3_1.eContents().get(0);
		private final RuleCall cOutgoingTransitionEStringParserRuleCall_5_3_1_0_1 = (RuleCall)cOutgoingTransitionCrossReference_5_3_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_5_4 = (Keyword)cGroup_5.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//ActivityNode:
		//	{ActivityNode}
		//	'ActivityNode'
		//	name=EString
		//	'{' ('incoming' '(' incoming+=[Transition|EString] ("," incoming+=[Transition|EString])* ')')? ('outgoing' '('
		//	outgoing+=[Transition|EString] ("," outgoing+=[Transition|EString])* ')')?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{ActivityNode} 'ActivityNode' name=EString '{' ('incoming' '(' incoming+=[Transition|EString] (","
		//incoming+=[Transition|EString])* ')')? ('outgoing' '(' outgoing+=[Transition|EString] (","
		//outgoing+=[Transition|EString])* ')')? '}'
		public Group getGroup() { return cGroup; }
		
		//{ActivityNode}
		public Action getActivityNodeAction_0() { return cActivityNodeAction_0; }
		
		//'ActivityNode'
		public Keyword getActivityNodeKeyword_1() { return cActivityNodeKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('incoming' '(' incoming+=[Transition|EString] ("," incoming+=[Transition|EString])* ')')?
		public Group getGroup_4() { return cGroup_4; }
		
		//'incoming'
		public Keyword getIncomingKeyword_4_0() { return cIncomingKeyword_4_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_4_1() { return cLeftParenthesisKeyword_4_1; }
		
		//incoming+=[Transition|EString]
		public Assignment getIncomingAssignment_4_2() { return cIncomingAssignment_4_2; }
		
		//[Transition|EString]
		public CrossReference getIncomingTransitionCrossReference_4_2_0() { return cIncomingTransitionCrossReference_4_2_0; }
		
		//EString
		public RuleCall getIncomingTransitionEStringParserRuleCall_4_2_0_1() { return cIncomingTransitionEStringParserRuleCall_4_2_0_1; }
		
		//("," incoming+=[Transition|EString])*
		public Group getGroup_4_3() { return cGroup_4_3; }
		
		//","
		public Keyword getCommaKeyword_4_3_0() { return cCommaKeyword_4_3_0; }
		
		//incoming+=[Transition|EString]
		public Assignment getIncomingAssignment_4_3_1() { return cIncomingAssignment_4_3_1; }
		
		//[Transition|EString]
		public CrossReference getIncomingTransitionCrossReference_4_3_1_0() { return cIncomingTransitionCrossReference_4_3_1_0; }
		
		//EString
		public RuleCall getIncomingTransitionEStringParserRuleCall_4_3_1_0_1() { return cIncomingTransitionEStringParserRuleCall_4_3_1_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_4_4() { return cRightParenthesisKeyword_4_4; }
		
		//('outgoing' '(' outgoing+=[Transition|EString] ("," outgoing+=[Transition|EString])* ')')?
		public Group getGroup_5() { return cGroup_5; }
		
		//'outgoing'
		public Keyword getOutgoingKeyword_5_0() { return cOutgoingKeyword_5_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_5_1() { return cLeftParenthesisKeyword_5_1; }
		
		//outgoing+=[Transition|EString]
		public Assignment getOutgoingAssignment_5_2() { return cOutgoingAssignment_5_2; }
		
		//[Transition|EString]
		public CrossReference getOutgoingTransitionCrossReference_5_2_0() { return cOutgoingTransitionCrossReference_5_2_0; }
		
		//EString
		public RuleCall getOutgoingTransitionEStringParserRuleCall_5_2_0_1() { return cOutgoingTransitionEStringParserRuleCall_5_2_0_1; }
		
		//("," outgoing+=[Transition|EString])*
		public Group getGroup_5_3() { return cGroup_5_3; }
		
		//","
		public Keyword getCommaKeyword_5_3_0() { return cCommaKeyword_5_3_0; }
		
		//outgoing+=[Transition|EString]
		public Assignment getOutgoingAssignment_5_3_1() { return cOutgoingAssignment_5_3_1; }
		
		//[Transition|EString]
		public CrossReference getOutgoingTransitionCrossReference_5_3_1_0() { return cOutgoingTransitionCrossReference_5_3_1_0; }
		
		//EString
		public RuleCall getOutgoingTransitionEStringParserRuleCall_5_3_1_0_1() { return cOutgoingTransitionEStringParserRuleCall_5_3_1_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_5_4() { return cRightParenthesisKeyword_5_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	public class ForkNodeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.activitydiagramdsl.ActivityDiagramDsl.ForkNode");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cForkNodeAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cForkNodeKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cIncomingKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cIncomingAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final CrossReference cIncomingTransitionCrossReference_4_2_0 = (CrossReference)cIncomingAssignment_4_2.eContents().get(0);
		private final RuleCall cIncomingTransitionEStringParserRuleCall_4_2_0_1 = (RuleCall)cIncomingTransitionCrossReference_4_2_0.eContents().get(1);
		private final Group cGroup_4_3 = (Group)cGroup_4.eContents().get(3);
		private final Keyword cCommaKeyword_4_3_0 = (Keyword)cGroup_4_3.eContents().get(0);
		private final Assignment cIncomingAssignment_4_3_1 = (Assignment)cGroup_4_3.eContents().get(1);
		private final CrossReference cIncomingTransitionCrossReference_4_3_1_0 = (CrossReference)cIncomingAssignment_4_3_1.eContents().get(0);
		private final RuleCall cIncomingTransitionEStringParserRuleCall_4_3_1_0_1 = (RuleCall)cIncomingTransitionCrossReference_4_3_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_4_4 = (Keyword)cGroup_4.eContents().get(4);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cOutgoingKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Assignment cOutgoingAssignment_5_2 = (Assignment)cGroup_5.eContents().get(2);
		private final CrossReference cOutgoingTransitionCrossReference_5_2_0 = (CrossReference)cOutgoingAssignment_5_2.eContents().get(0);
		private final RuleCall cOutgoingTransitionEStringParserRuleCall_5_2_0_1 = (RuleCall)cOutgoingTransitionCrossReference_5_2_0.eContents().get(1);
		private final Group cGroup_5_3 = (Group)cGroup_5.eContents().get(3);
		private final Keyword cCommaKeyword_5_3_0 = (Keyword)cGroup_5_3.eContents().get(0);
		private final Assignment cOutgoingAssignment_5_3_1 = (Assignment)cGroup_5_3.eContents().get(1);
		private final CrossReference cOutgoingTransitionCrossReference_5_3_1_0 = (CrossReference)cOutgoingAssignment_5_3_1.eContents().get(0);
		private final RuleCall cOutgoingTransitionEStringParserRuleCall_5_3_1_0_1 = (RuleCall)cOutgoingTransitionCrossReference_5_3_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_5_4 = (Keyword)cGroup_5.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//ForkNode:
		//	{ForkNode}
		//	'ForkNode'
		//	name=EString
		//	'{' ('incoming' '(' incoming+=[Transition|EString] ("," incoming+=[Transition|EString])* ')')? ('outgoing' '('
		//	outgoing+=[Transition|EString] ("," outgoing+=[Transition|EString])* ')')?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{ForkNode} 'ForkNode' name=EString '{' ('incoming' '(' incoming+=[Transition|EString] (","
		//incoming+=[Transition|EString])* ')')? ('outgoing' '(' outgoing+=[Transition|EString] (","
		//outgoing+=[Transition|EString])* ')')? '}'
		public Group getGroup() { return cGroup; }
		
		//{ForkNode}
		public Action getForkNodeAction_0() { return cForkNodeAction_0; }
		
		//'ForkNode'
		public Keyword getForkNodeKeyword_1() { return cForkNodeKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('incoming' '(' incoming+=[Transition|EString] ("," incoming+=[Transition|EString])* ')')?
		public Group getGroup_4() { return cGroup_4; }
		
		//'incoming'
		public Keyword getIncomingKeyword_4_0() { return cIncomingKeyword_4_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_4_1() { return cLeftParenthesisKeyword_4_1; }
		
		//incoming+=[Transition|EString]
		public Assignment getIncomingAssignment_4_2() { return cIncomingAssignment_4_2; }
		
		//[Transition|EString]
		public CrossReference getIncomingTransitionCrossReference_4_2_0() { return cIncomingTransitionCrossReference_4_2_0; }
		
		//EString
		public RuleCall getIncomingTransitionEStringParserRuleCall_4_2_0_1() { return cIncomingTransitionEStringParserRuleCall_4_2_0_1; }
		
		//("," incoming+=[Transition|EString])*
		public Group getGroup_4_3() { return cGroup_4_3; }
		
		//","
		public Keyword getCommaKeyword_4_3_0() { return cCommaKeyword_4_3_0; }
		
		//incoming+=[Transition|EString]
		public Assignment getIncomingAssignment_4_3_1() { return cIncomingAssignment_4_3_1; }
		
		//[Transition|EString]
		public CrossReference getIncomingTransitionCrossReference_4_3_1_0() { return cIncomingTransitionCrossReference_4_3_1_0; }
		
		//EString
		public RuleCall getIncomingTransitionEStringParserRuleCall_4_3_1_0_1() { return cIncomingTransitionEStringParserRuleCall_4_3_1_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_4_4() { return cRightParenthesisKeyword_4_4; }
		
		//('outgoing' '(' outgoing+=[Transition|EString] ("," outgoing+=[Transition|EString])* ')')?
		public Group getGroup_5() { return cGroup_5; }
		
		//'outgoing'
		public Keyword getOutgoingKeyword_5_0() { return cOutgoingKeyword_5_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_5_1() { return cLeftParenthesisKeyword_5_1; }
		
		//outgoing+=[Transition|EString]
		public Assignment getOutgoingAssignment_5_2() { return cOutgoingAssignment_5_2; }
		
		//[Transition|EString]
		public CrossReference getOutgoingTransitionCrossReference_5_2_0() { return cOutgoingTransitionCrossReference_5_2_0; }
		
		//EString
		public RuleCall getOutgoingTransitionEStringParserRuleCall_5_2_0_1() { return cOutgoingTransitionEStringParserRuleCall_5_2_0_1; }
		
		//("," outgoing+=[Transition|EString])*
		public Group getGroup_5_3() { return cGroup_5_3; }
		
		//","
		public Keyword getCommaKeyword_5_3_0() { return cCommaKeyword_5_3_0; }
		
		//outgoing+=[Transition|EString]
		public Assignment getOutgoingAssignment_5_3_1() { return cOutgoingAssignment_5_3_1; }
		
		//[Transition|EString]
		public CrossReference getOutgoingTransitionCrossReference_5_3_1_0() { return cOutgoingTransitionCrossReference_5_3_1_0; }
		
		//EString
		public RuleCall getOutgoingTransitionEStringParserRuleCall_5_3_1_0_1() { return cOutgoingTransitionEStringParserRuleCall_5_3_1_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_5_4() { return cRightParenthesisKeyword_5_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	public class JoinNodeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.activitydiagramdsl.ActivityDiagramDsl.JoinNode");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cJoinNodeAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cJoinNodeKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cIncomingKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cIncomingAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final CrossReference cIncomingTransitionCrossReference_4_2_0 = (CrossReference)cIncomingAssignment_4_2.eContents().get(0);
		private final RuleCall cIncomingTransitionEStringParserRuleCall_4_2_0_1 = (RuleCall)cIncomingTransitionCrossReference_4_2_0.eContents().get(1);
		private final Group cGroup_4_3 = (Group)cGroup_4.eContents().get(3);
		private final Keyword cCommaKeyword_4_3_0 = (Keyword)cGroup_4_3.eContents().get(0);
		private final Assignment cIncomingAssignment_4_3_1 = (Assignment)cGroup_4_3.eContents().get(1);
		private final CrossReference cIncomingTransitionCrossReference_4_3_1_0 = (CrossReference)cIncomingAssignment_4_3_1.eContents().get(0);
		private final RuleCall cIncomingTransitionEStringParserRuleCall_4_3_1_0_1 = (RuleCall)cIncomingTransitionCrossReference_4_3_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_4_4 = (Keyword)cGroup_4.eContents().get(4);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cOutgoingKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Assignment cOutgoingAssignment_5_2 = (Assignment)cGroup_5.eContents().get(2);
		private final CrossReference cOutgoingTransitionCrossReference_5_2_0 = (CrossReference)cOutgoingAssignment_5_2.eContents().get(0);
		private final RuleCall cOutgoingTransitionEStringParserRuleCall_5_2_0_1 = (RuleCall)cOutgoingTransitionCrossReference_5_2_0.eContents().get(1);
		private final Group cGroup_5_3 = (Group)cGroup_5.eContents().get(3);
		private final Keyword cCommaKeyword_5_3_0 = (Keyword)cGroup_5_3.eContents().get(0);
		private final Assignment cOutgoingAssignment_5_3_1 = (Assignment)cGroup_5_3.eContents().get(1);
		private final CrossReference cOutgoingTransitionCrossReference_5_3_1_0 = (CrossReference)cOutgoingAssignment_5_3_1.eContents().get(0);
		private final RuleCall cOutgoingTransitionEStringParserRuleCall_5_3_1_0_1 = (RuleCall)cOutgoingTransitionCrossReference_5_3_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_5_4 = (Keyword)cGroup_5.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//JoinNode:
		//	{JoinNode}
		//	'JoinNode'
		//	name=EString
		//	'{' ('incoming' '(' incoming+=[Transition|EString] ("," incoming+=[Transition|EString])* ')')? ('outgoing' '('
		//	outgoing+=[Transition|EString] ("," outgoing+=[Transition|EString])* ')')?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{JoinNode} 'JoinNode' name=EString '{' ('incoming' '(' incoming+=[Transition|EString] (","
		//incoming+=[Transition|EString])* ')')? ('outgoing' '(' outgoing+=[Transition|EString] (","
		//outgoing+=[Transition|EString])* ')')? '}'
		public Group getGroup() { return cGroup; }
		
		//{JoinNode}
		public Action getJoinNodeAction_0() { return cJoinNodeAction_0; }
		
		//'JoinNode'
		public Keyword getJoinNodeKeyword_1() { return cJoinNodeKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('incoming' '(' incoming+=[Transition|EString] ("," incoming+=[Transition|EString])* ')')?
		public Group getGroup_4() { return cGroup_4; }
		
		//'incoming'
		public Keyword getIncomingKeyword_4_0() { return cIncomingKeyword_4_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_4_1() { return cLeftParenthesisKeyword_4_1; }
		
		//incoming+=[Transition|EString]
		public Assignment getIncomingAssignment_4_2() { return cIncomingAssignment_4_2; }
		
		//[Transition|EString]
		public CrossReference getIncomingTransitionCrossReference_4_2_0() { return cIncomingTransitionCrossReference_4_2_0; }
		
		//EString
		public RuleCall getIncomingTransitionEStringParserRuleCall_4_2_0_1() { return cIncomingTransitionEStringParserRuleCall_4_2_0_1; }
		
		//("," incoming+=[Transition|EString])*
		public Group getGroup_4_3() { return cGroup_4_3; }
		
		//","
		public Keyword getCommaKeyword_4_3_0() { return cCommaKeyword_4_3_0; }
		
		//incoming+=[Transition|EString]
		public Assignment getIncomingAssignment_4_3_1() { return cIncomingAssignment_4_3_1; }
		
		//[Transition|EString]
		public CrossReference getIncomingTransitionCrossReference_4_3_1_0() { return cIncomingTransitionCrossReference_4_3_1_0; }
		
		//EString
		public RuleCall getIncomingTransitionEStringParserRuleCall_4_3_1_0_1() { return cIncomingTransitionEStringParserRuleCall_4_3_1_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_4_4() { return cRightParenthesisKeyword_4_4; }
		
		//('outgoing' '(' outgoing+=[Transition|EString] ("," outgoing+=[Transition|EString])* ')')?
		public Group getGroup_5() { return cGroup_5; }
		
		//'outgoing'
		public Keyword getOutgoingKeyword_5_0() { return cOutgoingKeyword_5_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_5_1() { return cLeftParenthesisKeyword_5_1; }
		
		//outgoing+=[Transition|EString]
		public Assignment getOutgoingAssignment_5_2() { return cOutgoingAssignment_5_2; }
		
		//[Transition|EString]
		public CrossReference getOutgoingTransitionCrossReference_5_2_0() { return cOutgoingTransitionCrossReference_5_2_0; }
		
		//EString
		public RuleCall getOutgoingTransitionEStringParserRuleCall_5_2_0_1() { return cOutgoingTransitionEStringParserRuleCall_5_2_0_1; }
		
		//("," outgoing+=[Transition|EString])*
		public Group getGroup_5_3() { return cGroup_5_3; }
		
		//","
		public Keyword getCommaKeyword_5_3_0() { return cCommaKeyword_5_3_0; }
		
		//outgoing+=[Transition|EString]
		public Assignment getOutgoingAssignment_5_3_1() { return cOutgoingAssignment_5_3_1; }
		
		//[Transition|EString]
		public CrossReference getOutgoingTransitionCrossReference_5_3_1_0() { return cOutgoingTransitionCrossReference_5_3_1_0; }
		
		//EString
		public RuleCall getOutgoingTransitionEStringParserRuleCall_5_3_1_0_1() { return cOutgoingTransitionEStringParserRuleCall_5_3_1_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_5_4() { return cRightParenthesisKeyword_5_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	public class DecisionNodeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.activitydiagramdsl.ActivityDiagramDsl.DecisionNode");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cDecisionNodeAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cDecisionNodeKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cIncomingKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cIncomingAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final CrossReference cIncomingTransitionCrossReference_4_2_0 = (CrossReference)cIncomingAssignment_4_2.eContents().get(0);
		private final RuleCall cIncomingTransitionEStringParserRuleCall_4_2_0_1 = (RuleCall)cIncomingTransitionCrossReference_4_2_0.eContents().get(1);
		private final Group cGroup_4_3 = (Group)cGroup_4.eContents().get(3);
		private final Keyword cCommaKeyword_4_3_0 = (Keyword)cGroup_4_3.eContents().get(0);
		private final Assignment cIncomingAssignment_4_3_1 = (Assignment)cGroup_4_3.eContents().get(1);
		private final CrossReference cIncomingTransitionCrossReference_4_3_1_0 = (CrossReference)cIncomingAssignment_4_3_1.eContents().get(0);
		private final RuleCall cIncomingTransitionEStringParserRuleCall_4_3_1_0_1 = (RuleCall)cIncomingTransitionCrossReference_4_3_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_4_4 = (Keyword)cGroup_4.eContents().get(4);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cOutgoingKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Assignment cOutgoingAssignment_5_2 = (Assignment)cGroup_5.eContents().get(2);
		private final CrossReference cOutgoingTransitionCrossReference_5_2_0 = (CrossReference)cOutgoingAssignment_5_2.eContents().get(0);
		private final RuleCall cOutgoingTransitionEStringParserRuleCall_5_2_0_1 = (RuleCall)cOutgoingTransitionCrossReference_5_2_0.eContents().get(1);
		private final Group cGroup_5_3 = (Group)cGroup_5.eContents().get(3);
		private final Keyword cCommaKeyword_5_3_0 = (Keyword)cGroup_5_3.eContents().get(0);
		private final Assignment cOutgoingAssignment_5_3_1 = (Assignment)cGroup_5_3.eContents().get(1);
		private final CrossReference cOutgoingTransitionCrossReference_5_3_1_0 = (CrossReference)cOutgoingAssignment_5_3_1.eContents().get(0);
		private final RuleCall cOutgoingTransitionEStringParserRuleCall_5_3_1_0_1 = (RuleCall)cOutgoingTransitionCrossReference_5_3_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_5_4 = (Keyword)cGroup_5.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//DecisionNode:
		//	{DecisionNode}
		//	'DecisionNode'
		//	name=EString
		//	'{' ('incoming' '(' incoming+=[Transition|EString] ("," incoming+=[Transition|EString])* ')')? ('outgoing' '('
		//	outgoing+=[Transition|EString] ("," outgoing+=[Transition|EString])* ')')?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{DecisionNode} 'DecisionNode' name=EString '{' ('incoming' '(' incoming+=[Transition|EString] (","
		//incoming+=[Transition|EString])* ')')? ('outgoing' '(' outgoing+=[Transition|EString] (","
		//outgoing+=[Transition|EString])* ')')? '}'
		public Group getGroup() { return cGroup; }
		
		//{DecisionNode}
		public Action getDecisionNodeAction_0() { return cDecisionNodeAction_0; }
		
		//'DecisionNode'
		public Keyword getDecisionNodeKeyword_1() { return cDecisionNodeKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('incoming' '(' incoming+=[Transition|EString] ("," incoming+=[Transition|EString])* ')')?
		public Group getGroup_4() { return cGroup_4; }
		
		//'incoming'
		public Keyword getIncomingKeyword_4_0() { return cIncomingKeyword_4_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_4_1() { return cLeftParenthesisKeyword_4_1; }
		
		//incoming+=[Transition|EString]
		public Assignment getIncomingAssignment_4_2() { return cIncomingAssignment_4_2; }
		
		//[Transition|EString]
		public CrossReference getIncomingTransitionCrossReference_4_2_0() { return cIncomingTransitionCrossReference_4_2_0; }
		
		//EString
		public RuleCall getIncomingTransitionEStringParserRuleCall_4_2_0_1() { return cIncomingTransitionEStringParserRuleCall_4_2_0_1; }
		
		//("," incoming+=[Transition|EString])*
		public Group getGroup_4_3() { return cGroup_4_3; }
		
		//","
		public Keyword getCommaKeyword_4_3_0() { return cCommaKeyword_4_3_0; }
		
		//incoming+=[Transition|EString]
		public Assignment getIncomingAssignment_4_3_1() { return cIncomingAssignment_4_3_1; }
		
		//[Transition|EString]
		public CrossReference getIncomingTransitionCrossReference_4_3_1_0() { return cIncomingTransitionCrossReference_4_3_1_0; }
		
		//EString
		public RuleCall getIncomingTransitionEStringParserRuleCall_4_3_1_0_1() { return cIncomingTransitionEStringParserRuleCall_4_3_1_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_4_4() { return cRightParenthesisKeyword_4_4; }
		
		//('outgoing' '(' outgoing+=[Transition|EString] ("," outgoing+=[Transition|EString])* ')')?
		public Group getGroup_5() { return cGroup_5; }
		
		//'outgoing'
		public Keyword getOutgoingKeyword_5_0() { return cOutgoingKeyword_5_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_5_1() { return cLeftParenthesisKeyword_5_1; }
		
		//outgoing+=[Transition|EString]
		public Assignment getOutgoingAssignment_5_2() { return cOutgoingAssignment_5_2; }
		
		//[Transition|EString]
		public CrossReference getOutgoingTransitionCrossReference_5_2_0() { return cOutgoingTransitionCrossReference_5_2_0; }
		
		//EString
		public RuleCall getOutgoingTransitionEStringParserRuleCall_5_2_0_1() { return cOutgoingTransitionEStringParserRuleCall_5_2_0_1; }
		
		//("," outgoing+=[Transition|EString])*
		public Group getGroup_5_3() { return cGroup_5_3; }
		
		//","
		public Keyword getCommaKeyword_5_3_0() { return cCommaKeyword_5_3_0; }
		
		//outgoing+=[Transition|EString]
		public Assignment getOutgoingAssignment_5_3_1() { return cOutgoingAssignment_5_3_1; }
		
		//[Transition|EString]
		public CrossReference getOutgoingTransitionCrossReference_5_3_1_0() { return cOutgoingTransitionCrossReference_5_3_1_0; }
		
		//EString
		public RuleCall getOutgoingTransitionEStringParserRuleCall_5_3_1_0_1() { return cOutgoingTransitionEStringParserRuleCall_5_3_1_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_5_4() { return cRightParenthesisKeyword_5_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	public class Node_ImplElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.activitydiagramdsl.ActivityDiagramDsl.Node_Impl");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cNodeAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cNodeKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cIncomingKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cIncomingAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final CrossReference cIncomingTransitionCrossReference_4_2_0 = (CrossReference)cIncomingAssignment_4_2.eContents().get(0);
		private final RuleCall cIncomingTransitionEStringParserRuleCall_4_2_0_1 = (RuleCall)cIncomingTransitionCrossReference_4_2_0.eContents().get(1);
		private final Group cGroup_4_3 = (Group)cGroup_4.eContents().get(3);
		private final Keyword cCommaKeyword_4_3_0 = (Keyword)cGroup_4_3.eContents().get(0);
		private final Assignment cIncomingAssignment_4_3_1 = (Assignment)cGroup_4_3.eContents().get(1);
		private final CrossReference cIncomingTransitionCrossReference_4_3_1_0 = (CrossReference)cIncomingAssignment_4_3_1.eContents().get(0);
		private final RuleCall cIncomingTransitionEStringParserRuleCall_4_3_1_0_1 = (RuleCall)cIncomingTransitionCrossReference_4_3_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_4_4 = (Keyword)cGroup_4.eContents().get(4);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cOutgoingKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Assignment cOutgoingAssignment_5_2 = (Assignment)cGroup_5.eContents().get(2);
		private final CrossReference cOutgoingTransitionCrossReference_5_2_0 = (CrossReference)cOutgoingAssignment_5_2.eContents().get(0);
		private final RuleCall cOutgoingTransitionEStringParserRuleCall_5_2_0_1 = (RuleCall)cOutgoingTransitionCrossReference_5_2_0.eContents().get(1);
		private final Group cGroup_5_3 = (Group)cGroup_5.eContents().get(3);
		private final Keyword cCommaKeyword_5_3_0 = (Keyword)cGroup_5_3.eContents().get(0);
		private final Assignment cOutgoingAssignment_5_3_1 = (Assignment)cGroup_5_3.eContents().get(1);
		private final CrossReference cOutgoingTransitionCrossReference_5_3_1_0 = (CrossReference)cOutgoingAssignment_5_3_1.eContents().get(0);
		private final RuleCall cOutgoingTransitionEStringParserRuleCall_5_3_1_0_1 = (RuleCall)cOutgoingTransitionCrossReference_5_3_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_5_4 = (Keyword)cGroup_5.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//Node_Impl Node:
		//	{Node}
		//	'Node'
		//	name=EString
		//	'{' ('incoming' '(' incoming+=[Transition|EString] ("," incoming+=[Transition|EString])* ')')? ('outgoing' '('
		//	outgoing+=[Transition|EString] ("," outgoing+=[Transition|EString])* ')')?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Node} 'Node' name=EString '{' ('incoming' '(' incoming+=[Transition|EString] ("," incoming+=[Transition|EString])*
		//')')? ('outgoing' '(' outgoing+=[Transition|EString] ("," outgoing+=[Transition|EString])* ')')? '}'
		public Group getGroup() { return cGroup; }
		
		//{Node}
		public Action getNodeAction_0() { return cNodeAction_0; }
		
		//'Node'
		public Keyword getNodeKeyword_1() { return cNodeKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('incoming' '(' incoming+=[Transition|EString] ("," incoming+=[Transition|EString])* ')')?
		public Group getGroup_4() { return cGroup_4; }
		
		//'incoming'
		public Keyword getIncomingKeyword_4_0() { return cIncomingKeyword_4_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_4_1() { return cLeftParenthesisKeyword_4_1; }
		
		//incoming+=[Transition|EString]
		public Assignment getIncomingAssignment_4_2() { return cIncomingAssignment_4_2; }
		
		//[Transition|EString]
		public CrossReference getIncomingTransitionCrossReference_4_2_0() { return cIncomingTransitionCrossReference_4_2_0; }
		
		//EString
		public RuleCall getIncomingTransitionEStringParserRuleCall_4_2_0_1() { return cIncomingTransitionEStringParserRuleCall_4_2_0_1; }
		
		//("," incoming+=[Transition|EString])*
		public Group getGroup_4_3() { return cGroup_4_3; }
		
		//","
		public Keyword getCommaKeyword_4_3_0() { return cCommaKeyword_4_3_0; }
		
		//incoming+=[Transition|EString]
		public Assignment getIncomingAssignment_4_3_1() { return cIncomingAssignment_4_3_1; }
		
		//[Transition|EString]
		public CrossReference getIncomingTransitionCrossReference_4_3_1_0() { return cIncomingTransitionCrossReference_4_3_1_0; }
		
		//EString
		public RuleCall getIncomingTransitionEStringParserRuleCall_4_3_1_0_1() { return cIncomingTransitionEStringParserRuleCall_4_3_1_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_4_4() { return cRightParenthesisKeyword_4_4; }
		
		//('outgoing' '(' outgoing+=[Transition|EString] ("," outgoing+=[Transition|EString])* ')')?
		public Group getGroup_5() { return cGroup_5; }
		
		//'outgoing'
		public Keyword getOutgoingKeyword_5_0() { return cOutgoingKeyword_5_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_5_1() { return cLeftParenthesisKeyword_5_1; }
		
		//outgoing+=[Transition|EString]
		public Assignment getOutgoingAssignment_5_2() { return cOutgoingAssignment_5_2; }
		
		//[Transition|EString]
		public CrossReference getOutgoingTransitionCrossReference_5_2_0() { return cOutgoingTransitionCrossReference_5_2_0; }
		
		//EString
		public RuleCall getOutgoingTransitionEStringParserRuleCall_5_2_0_1() { return cOutgoingTransitionEStringParserRuleCall_5_2_0_1; }
		
		//("," outgoing+=[Transition|EString])*
		public Group getGroup_5_3() { return cGroup_5_3; }
		
		//","
		public Keyword getCommaKeyword_5_3_0() { return cCommaKeyword_5_3_0; }
		
		//outgoing+=[Transition|EString]
		public Assignment getOutgoingAssignment_5_3_1() { return cOutgoingAssignment_5_3_1; }
		
		//[Transition|EString]
		public CrossReference getOutgoingTransitionCrossReference_5_3_1_0() { return cOutgoingTransitionCrossReference_5_3_1_0; }
		
		//EString
		public RuleCall getOutgoingTransitionEStringParserRuleCall_5_3_1_0_1() { return cOutgoingTransitionEStringParserRuleCall_5_3_1_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_5_4() { return cRightParenthesisKeyword_5_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	
	
	private final ActivityDiagramElements pActivityDiagram;
	private final NodeElements pNode;
	private final EStringElements pEString;
	private final InitialNodeElements pInitialNode;
	private final FinalNodeElements pFinalNode;
	private final TransitionElements pTransition;
	private final ActivityNodeElements pActivityNode;
	private final ForkNodeElements pForkNode;
	private final JoinNodeElements pJoinNode;
	private final DecisionNodeElements pDecisionNode;
	private final Node_ImplElements pNode_Impl;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public ActivityDiagramDslGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pActivityDiagram = new ActivityDiagramElements();
		this.pNode = new NodeElements();
		this.pEString = new EStringElements();
		this.pInitialNode = new InitialNodeElements();
		this.pFinalNode = new FinalNodeElements();
		this.pTransition = new TransitionElements();
		this.pActivityNode = new ActivityNodeElements();
		this.pForkNode = new ForkNodeElements();
		this.pJoinNode = new JoinNodeElements();
		this.pDecisionNode = new DecisionNodeElements();
		this.pNode_Impl = new Node_ImplElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.xtext.example.activitydiagramdsl.ActivityDiagramDsl".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//ActivityDiagram:
	//	{ActivityDiagram}
	//	'ActivityDiagram'
	//	name=EString
	//	'{' ('initialNode' initialNode=InitialNode)? ('finalNode' finalNode=FinalNode)? ('trasitions' '{'
	//	trasitions+=Transition ("," trasitions+=Transition)* '}')? ('activityNodes' '{' activityNodes+=ActivityNode (","
	//	activityNodes+=ActivityNode)* '}')? ('forkNodes' '{' forkNodes+=ForkNode ("," forkNodes+=ForkNode)* '}')?
	//	('joinNodes' '{' joinNodes+=JoinNode ("," joinNodes+=JoinNode)* '}')? ('decisionNodes' '{'
	//	decisionNodes+=DecisionNode ("," decisionNodes+=DecisionNode)* '}')?
	//	'}';
	public ActivityDiagramElements getActivityDiagramAccess() {
		return pActivityDiagram;
	}
	
	public ParserRule getActivityDiagramRule() {
		return getActivityDiagramAccess().getRule();
	}
	
	//Node:
	//	Node_Impl | FinalNode | InitialNode | ActivityNode | DecisionNode | ForkNode | JoinNode;
	public NodeElements getNodeAccess() {
		return pNode;
	}
	
	public ParserRule getNodeRule() {
		return getNodeAccess().getRule();
	}
	
	//EString:
	//	STRING | ID;
	public EStringElements getEStringAccess() {
		return pEString;
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}
	
	//InitialNode:
	//	{InitialNode}
	//	'InitialNode'
	//	name=EString
	//	'{' ('incoming' '(' incoming+=[Transition|EString] ("," incoming+=[Transition|EString])* ')')? ('outgoing' '('
	//	outgoing+=[Transition|EString] ("," outgoing+=[Transition|EString])* ')')?
	//	'}';
	public InitialNodeElements getInitialNodeAccess() {
		return pInitialNode;
	}
	
	public ParserRule getInitialNodeRule() {
		return getInitialNodeAccess().getRule();
	}
	
	//FinalNode:
	//	{FinalNode}
	//	'FinalNode'
	//	name=EString
	//	'{' ('incoming' '(' incoming+=[Transition|EString] ("," incoming+=[Transition|EString])* ')')? ('outgoing' '('
	//	outgoing+=[Transition|EString] ("," outgoing+=[Transition|EString])* ')')?
	//	'}';
	public FinalNodeElements getFinalNodeAccess() {
		return pFinalNode;
	}
	
	public ParserRule getFinalNodeRule() {
		return getFinalNodeAccess().getRule();
	}
	
	//Transition:
	//	{Transition}
	//	'Transition'
	//	name=EString
	//	'{' ('target' target=[Node|EString])? ('source' source=[Node|EString])?
	//	'}';
	public TransitionElements getTransitionAccess() {
		return pTransition;
	}
	
	public ParserRule getTransitionRule() {
		return getTransitionAccess().getRule();
	}
	
	//ActivityNode:
	//	{ActivityNode}
	//	'ActivityNode'
	//	name=EString
	//	'{' ('incoming' '(' incoming+=[Transition|EString] ("," incoming+=[Transition|EString])* ')')? ('outgoing' '('
	//	outgoing+=[Transition|EString] ("," outgoing+=[Transition|EString])* ')')?
	//	'}';
	public ActivityNodeElements getActivityNodeAccess() {
		return pActivityNode;
	}
	
	public ParserRule getActivityNodeRule() {
		return getActivityNodeAccess().getRule();
	}
	
	//ForkNode:
	//	{ForkNode}
	//	'ForkNode'
	//	name=EString
	//	'{' ('incoming' '(' incoming+=[Transition|EString] ("," incoming+=[Transition|EString])* ')')? ('outgoing' '('
	//	outgoing+=[Transition|EString] ("," outgoing+=[Transition|EString])* ')')?
	//	'}';
	public ForkNodeElements getForkNodeAccess() {
		return pForkNode;
	}
	
	public ParserRule getForkNodeRule() {
		return getForkNodeAccess().getRule();
	}
	
	//JoinNode:
	//	{JoinNode}
	//	'JoinNode'
	//	name=EString
	//	'{' ('incoming' '(' incoming+=[Transition|EString] ("," incoming+=[Transition|EString])* ')')? ('outgoing' '('
	//	outgoing+=[Transition|EString] ("," outgoing+=[Transition|EString])* ')')?
	//	'}';
	public JoinNodeElements getJoinNodeAccess() {
		return pJoinNode;
	}
	
	public ParserRule getJoinNodeRule() {
		return getJoinNodeAccess().getRule();
	}
	
	//DecisionNode:
	//	{DecisionNode}
	//	'DecisionNode'
	//	name=EString
	//	'{' ('incoming' '(' incoming+=[Transition|EString] ("," incoming+=[Transition|EString])* ')')? ('outgoing' '('
	//	outgoing+=[Transition|EString] ("," outgoing+=[Transition|EString])* ')')?
	//	'}';
	public DecisionNodeElements getDecisionNodeAccess() {
		return pDecisionNode;
	}
	
	public ParserRule getDecisionNodeRule() {
		return getDecisionNodeAccess().getRule();
	}
	
	//Node_Impl Node:
	//	{Node}
	//	'Node'
	//	name=EString
	//	'{' ('incoming' '(' incoming+=[Transition|EString] ("," incoming+=[Transition|EString])* ')')? ('outgoing' '('
	//	outgoing+=[Transition|EString] ("," outgoing+=[Transition|EString])* ')')?
	//	'}';
	public Node_ImplElements getNode_ImplAccess() {
		return pNode_Impl;
	}
	
	public ParserRule getNode_ImplRule() {
		return getNode_ImplAccess().getRule();
	}
	
	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"' | "'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT:
	//	'/*'->'*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
