/**
 * generated by Xtext 2.14.0
 */
package org.xtext.example.activitydiagramdsl.ui.contentassist;

import org.xtext.example.activitydiagramdsl.ui.contentassist.AbstractActivityDiagramDslProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class ActivityDiagramDslProposalProvider extends AbstractActivityDiagramDslProposalProvider {
}
