/*
 * generated by Xtext 2.14.0
 */
package org.xtext.example.activitydiagramdsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractActivityDiagramDslScopeProvider extends DelegatingScopeProvider {
}
